spring:
  datasource:
    url: jdbc:mysql://localhost:3306/obwiki?useSSL=false&characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    password: redis密码
  # rocketmq配置
  rocketmq:
    name-server: 127.0.0.1:9876
    producer:
      group: default
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.gec.obwiki.entity
  # 驼峰命名
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 端口 WEB
server:
  port: 8080

